better status bar

diff --git a/i3/.config/i3blocks/scripts/cpu b/i3/.config/i3blocks/scripts/cpu
--- a/i3/.config/i3blocks/scripts/cpu
+++ b/i3/.config/i3blocks/scripts/cpu
@@ -15,9 +15,9 @@ PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:${PATH}"
 ###
 ### Custom Defines
 ###
-appname="memory"
+appname="cpu"
 #time="${BLOCK_INSTANCE:-%H:%M}"
-format=" {used}{uunit} iB used"
+format=" {speed} {uspeed} ({percent}%)"
 
 
 ###
@@ -54,44 +54,39 @@ arg_desc_long=(
 
 # bash variable names
 format_vars=(
-	used
-	free
-	total
-	pused
-	pfree
-	uunit
-	funit
-	tunit
+	"speed"
+	"uspeed"
+	"percent"
+	"usage5"
+	"usage10"
+	"usage15"
 )
 
 # Format placeholders
 format_nodes=(
-	"{used}"
-	"{free}"
-	"{total}"
-	"{pused}"
-	"{pfree}"
-	"{uunit}"
-	"{funit}"
-	"{tunit}"
+	"{speed}"
+	"{uspeed}"
+	"{percent}"
+	"{usage5}"
+	"{usage10}"
+	"{usage15}"
 )
 
 # Format description (for help display)
 format_descs=(
-	"Used memory"
-	"Free memory"
-	"Total memory"
-	"Percent of used memory"
-	"Percent of free memory"
-	"Unit of used memory (K, M, G...)"
-	"Unit of free memory (K, M, G...)"
-	"Unit of total memory (K, M, G...)"
+	"Current CPU speed"
+	"Unit of urrent CPU speed (e.g.: 'GHz')"
+	"Current cpu usage in percent"
+	"Load avg last 5min"
+	"Load avg last 10min"
+	"Load avg last 15min"
 )
 
 # Format examples (for help display)
 format_examples=(
-	"-f \" {used} {punit}\""
-	"-f \"RAM: {used} {punit} of {total} {tunit} ({pused}%)\""
+	"-f \" {speed} {uspeed} ({percent}%)\""
+	"-f \" {usage5}\""
+	"-f \" {usage15}\""
 )
 
 
@@ -103,17 +98,31 @@ format_examples=(
 ### Evaluate disk space
 ###
 custom_action() {
-	local _dump
-	_dump="$( free | grep 'Mem' || true )"
+	local _cpufreq
+	local _percent
+	local _usage
 
-	total="$( echo "${_dump}" | awk '{printf("%.2f\n", $2/(1024*1024))}' )"
-	free="$(  echo "${_dump}" | awk '{printf("%.2f\n", $7/(1024*1024))}' )"
-	used="$(  awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%.2f\n", total-free)}' )"
-	pused="$( awk -v total="${total}" -v used="${used}" 'BEGIN {printf("%0.f\n", 100*used/total)}' )"
-	pfree="$( awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%0.f\n", 100*free/total)}' )"
-	uunit="G"
-	funit="G"
-	tunit="G"
+	if ! command -v cpufreq-info >/dev/null 2>&1; then
+		echo "Error, cpufreq-info binary not found, but required"
+		exit 1
+	fi
+
+	_cpufreq="$( cpufreq-info -fm )"
+	_percent="$( awk -v a="$(awk '/cpu /{print $2+$4,$2+$4+$5}' /proc/stat; sleep 1)" '/cpu /{split(a,b," "); print 100*($2+$4-b[1])/($2+$4+$5-b[2])}'  /proc/stat )"
+	_usage="$( uptime  | sed 's/.*:\s*//g' )"
+
+	speed="$( echo "${_cpufreq}" | grep -oE '[.0-9]+' || true )"
+	uspeed="${_cpufreq//*[[:space:]]/}"
+	percent="$( LC_ALL=C printf "%02.*f\\n" "0" "${_percent}" )"
+	usage5="$(  echo "${_usage}" | awk '{print $1}' | sed 's/,//g' )"
+	usage10="$( echo "${_usage}" | awk '{print $2}' | sed 's/,//g' )"
+	usage15="$( echo "${_usage}" | awk '{print $3}' | sed 's/,//g' )"
+
+	if [ "${uspeed}" = "MHz" ]; then
+		uspeed="GHz"
+		speed="$( awk -v mhz="${speed}" 'BEGIN{ printf("%.2f", mhz / 1000) }' )"
+	fi
+
 }
 
 
diff --git a/i3/.config/i3blocks/scripts/volume b/i3/.config/i3blocks/scripts/volume
--- a/i3/.config/i3blocks/scripts/volume
+++ b/i3/.config/i3blocks/scripts/volume
@@ -15,9 +15,8 @@ PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:${PATH}"
 ###
 ### Custom Defines
 ###
-appname="memory"
-#time="${BLOCK_INSTANCE:-%H:%M}"
-format=" {used}{uunit} iB used"
+appname="volume"
+format=" {volume}%"
 
 
 ###
@@ -39,14 +38,21 @@ force_good=0
 ### Additional arguments
 ###
 arg_params=(
+	-id
+	-im
 )
 arg_vars=(
+	icon_default
+	icon_mute
 )
 arg_desc_val=(
+	"<char>"
+	"<char>"
 )
 arg_desc_long=(
+	"Set default {icon} placeholder"
+	"Set muted {icon} placeholder"
 )
-
 
 ###
 ### Format placeholders
@@ -54,44 +60,62 @@ arg_desc_long=(
 
 # bash variable names
 format_vars=(
-	used
-	free
-	total
-	pused
-	pfree
-	uunit
-	funit
-	tunit
+	volume
+	muted
+	port
+	dev_api
+	dev_bus
+	dev_form_factor
+	dev_profile
+	dev_icon_name
+	dev_description
+	alsa_name
+	alsa_card
+	alsa_driver
+	alsa_mixer
+	icon
 )
 
 # Format placeholders
 format_nodes=(
-	"{used}"
-	"{free}"
-	"{total}"
-	"{pused}"
-	"{pfree}"
-	"{uunit}"
-	"{funit}"
-	"{tunit}"
+	"{volume}"
+	"{muted}"
+	"{port}"
+	"{dev_api}"
+	"{dev_bus}"
+	"{dev_form_factor}"
+	"{dev_profile}"
+	"{dev_icon_name}"
+	"{dev_description}"
+	"{alsa_name}"
+	"{alsa_card}"
+	"{alsa_driver}"
+	"{alsa_mixer}"
+	"{icon}"
 )
 
 # Format description (for help display)
 format_descs=(
-	"Used memory"
-	"Free memory"
-	"Total memory"
-	"Percent of used memory"
-	"Percent of free memory"
-	"Unit of used memory (K, M, G...)"
-	"Unit of free memory (K, M, G...)"
-	"Unit of total memory (K, M, G...)"
+	"{volume}"
+	"{muted}"
+	"{port}"
+	"{dev_api}"
+	"{dev_bus}"
+	"{dev_form_factor}"
+	"{dev_profile}"
+	"{dev_icon_name}"
+	"{dev_description}"
+	"{alsa_name}"
+	"{alsa_card}"
+	"{alsa_driver}"
+	"{alsa_mixer}"
+	"{icon}"
 )
 
 # Format examples (for help display)
 format_examples=(
-	"-f \" {used} {punit}\""
-	"-f \"RAM: {used} {punit} of {total} {tunit} ({pused}%)\""
+	"-f \" {volume}%\""
+	"-f \" {volume}% ({muted})\""
 )
 
 
@@ -103,17 +127,75 @@ format_examples=(
 ### Evaluate disk space
 ###
 custom_action() {
-	local _dump
-	_dump="$( free | grep 'Mem' || true )"
+	if ! command -v pactl > /dev/null 2>&1; then
+		echo "Binary pactl not found, but required."
+		exit 1
+	fi
 
-	total="$( echo "${_dump}" | awk '{printf("%.2f\n", $2/(1024*1024))}' )"
-	free="$(  echo "${_dump}" | awk '{printf("%.2f\n", $7/(1024*1024))}' )"
-	used="$(  awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%.2f\n", total-free)}' )"
-	pused="$( awk -v total="${total}" -v used="${used}" 'BEGIN {printf("%0.f\n", 100*used/total)}' )"
-	pfree="$( awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%0.f\n", 100*free/total)}' )"
-	uunit="G"
-	funit="G"
-	tunit="G"
+	###
+	### Get active sinkd
+	###
+	local sinks=()
+	local i=
+	local active=
+	local output=""
+
+	#Set the field separator to new line
+	IFS=$'\n'
+	for line in $( pactl list sinks ); do
+		# This line indicates a new sink
+		if [[ "${line}" =~ ^Sink[[:space:]]#[0-9]+$ ]]; then
+			if [ "${i}" = "" ]; then
+				# Initialize counter for first sync
+				i=0
+			else
+				# Increment sync counter
+				i=$(( i + 1 ))
+			fi
+		fi
+		# If i was initialized
+		if [ "${i}" != "" ]; then
+			sinks[${i}]="${sinks[${i}]}\\n${line}"
+
+			# Set active sink
+			if [[ "${line}" =~  State:[[:space:]]RUNNING ]]; then
+				active="${i}"
+			fi
+		fi
+	done
+
+	###
+	### Get active
+	###
+	output="$( echo -e "${sinks[${active}]}" )"
+
+	###
+	### Get global variables
+	###
+	volume="$( echo "${output}" | grep '^[[:space:]]*Volume:' | grep -oE '[0-9]+%' | head -1 | grep -oE '[0-9]+' || true )"
+	muted="$( echo "${output}" | grep '^[[:space:]]*Mute:' | sed 's/^.*:\s//g' )"
+	port="$( echo "${output}" | grep 'Active Port:' | sed 's/.*:\s*//g' )"
+
+	dev_api="$( echo "${output}" | grep 'device.api[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	dev_bus="$( echo "${output}" | grep 'device.bus[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	dev_form_factor="$( echo "${output}" | grep 'device.form_factor[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	dev_profile="$( echo "${output}" | grep 'device.profile.name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	dev_icon_name="$( echo "${output}" | grep 'device.icon_name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	dev_description="$( echo "${output}" | grep 'device.description[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+
+	alsa_name="$( echo "${output}" | grep 'alsa.name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	alsa_card="$( echo "${output}" | grep 'alsa.card_name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	alsa_driver="$( echo "${output}" | grep 'alsa.driver_name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+	alsa_mixer="$( echo "${output}" | grep 'alsa.mixer_name[[:space:]]' | grep -oE '".*"' | sed 's/"//g' )"
+
+
+	if [ "${muted}" = "yes" ]; then
+		# shellcheck disable=SC2154
+		icon="${icon_mute}"
+	else
+		# shellcheck disable=SC2154
+		icon="${icon_default}"
+	fi
 }
 
 
diff --git a/i3/.config/i3blocks/scripts/weather b/i3/.config/i3blocks/scripts/weather
--- a/i3/.config/i3blocks/scripts/weather
+++ b/i3/.config/i3blocks/scripts/weather
@@ -15,9 +15,9 @@ PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:${PATH}"
 ###
 ### Custom Defines
 ###
-appname="memory"
-#time="${BLOCK_INSTANCE:-%H:%M}"
-format=" {used}{uunit} iB used"
+appname="weather"
+city="${BLOCK_INSTANCE:-}"
+format="{icon_weather} {celsius} °C"
 
 
 ###
@@ -39,12 +39,16 @@ force_good=0
 ### Additional arguments
 ###
 arg_params=(
+	"-c"
 )
 arg_vars=(
+	"city"
 )
 arg_desc_val=(
+	"<city>"
 )
 arg_desc_long=(
+	"Specify the city to get the temperature from. This can also be set via i3blocks 'instance=' value."
 )
 
 
@@ -54,44 +58,41 @@ arg_desc_long=(
 
 # bash variable names
 format_vars=(
-	used
-	free
-	total
-	pused
-	pfree
-	uunit
-	funit
-	tunit
+	celsius
+	fahrenheit
+	wind_speed_kmh
+	wind_speed_mph
+	icon_weather
+	icon_wind_speed
+	icon_wind_direction
 )
 
 # Format placeholders
 format_nodes=(
-	"{used}"
-	"{free}"
-	"{total}"
-	"{pused}"
-	"{pfree}"
-	"{uunit}"
-	"{funit}"
-	"{tunit}"
+	"{celsius}"
+	"{fahrenheit}"
+	"{wind_speed_kmh}"
+	"{wind_speed_mph}"
+	"{icon_weather}"
+	"{icon_wind_speed}"
+	"{icon_wind_direction}"
 )
 
 # Format description (for help display)
 format_descs=(
-	"Used memory"
-	"Free memory"
-	"Total memory"
-	"Percent of used memory"
-	"Percent of free memory"
-	"Unit of used memory (K, M, G...)"
-	"Unit of free memory (K, M, G...)"
-	"Unit of total memory (K, M, G...)"
+	"Temperature in celsius"
+	"Temperature in fahrenheit"
+	"Wind speed in km per hour"
+	"Wind speed in miles per hour"
+	"Icon for weather: cloud, snow, etc"
+	"Icon for wind speed"
+	"Icon for wind direction"
 )
 
 # Format examples (for help display)
 format_examples=(
-	"-f \" {used} {punit}\""
-	"-f \"RAM: {used} {punit} of {total} {tunit} ({pused}%)\""
+	"-f \"{celsius} °C\""
+	"-f \"{fahrenheit} °F\""
 )
 
 
@@ -103,17 +104,103 @@ format_examples=(
 ### Evaluate disk space
 ###
 custom_action() {
-	local _dump
-	_dump="$( free | grep 'Mem' || true )"
+	local cache="${HOME}/.cache/i3blocks-modules/"
+	local file="${cache}/${appname}.${city}.cache"
 
-	total="$( echo "${_dump}" | awk '{printf("%.2f\n", $2/(1024*1024))}' )"
-	free="$(  echo "${_dump}" | awk '{printf("%.2f\n", $7/(1024*1024))}' )"
-	used="$(  awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%.2f\n", total-free)}' )"
-	pused="$( awk -v total="${total}" -v used="${used}" 'BEGIN {printf("%0.f\n", 100*used/total)}' )"
-	pfree="$( awk -v total="${total}" -v free="${free}" 'BEGIN {printf("%0.f\n", 100*free/total)}' )"
-	uunit="G"
-	funit="G"
-	tunit="G"
+	if ! command -v curl > /dev/null 2>&1; then
+		echo "Error, curl is required for this module."
+	fi
+
+	# Caching directory for offline price
+	if [ ! -d "${cache}" ]; then
+		mkdir "${cache}"
+	fi
+
+	###
+	### wttr.in
+	###
+	url_icon="wttr.in/${city}?format=2"
+	url_data="wttr.in/${city}?format=j1"
+	succ=1
+
+	# Get icons
+	if ! raw_icon="$( curl -sS --fail "${url_icon}")"; then
+		succ=0
+	else
+		icon_weather="$( echo "${raw_icon}" | awk '{print $1}' )"
+		icon_wind_speed="$( echo "${raw_icon}" | awk '{print $3}' | grep -Eo '^.{1}' )"
+		icon_wind_direction="$( echo "${raw_icon}" | awk '{print $3}' | rev | grep -Eo '[0-9].*$' | sed 's/[0-9]*//g' | grep -Eo '^.{1}' )"
+	fi
+
+	# Get data
+	if ! raw_data="$( curl -sS --fail "${url_data}" )"; then
+		succ=0
+	else
+		if ! echo "${raw_data}" | grep '"current_condition":' >/dev/null; then
+			succ=0
+		else
+			celsius="$( echo "${raw_data}" \
+				| grep temp_C \
+				| head -1 \
+				| awk -F':' '{print $2}' \
+				| grep -Eo '\-?[0-9]+'
+			)"
+			fahrenheit="$( echo "${raw_data}" \
+				| grep temp_F \
+				| head -1 \
+				| awk -F':' '{print $2}' \
+				| grep -Eo '\-?[0-9]+'
+			)"
+			wind_speed_kmh="$( echo "${raw_data}" \
+				| grep windspeedKmph \
+				| head -1 \
+				| awk -F':' '{print $2}' \
+				| grep -Eo '[0-9]+'
+			)"
+			wind_speed_mph="$( echo "${raw_data}" \
+				| grep windspeedMiles \
+				| head -1 \
+				| awk -F':' '{print $2}' \
+				| grep -Eo '[0-9]+'
+			)"
+		fi
+	fi
+	if [ "${succ}" -eq "1" ]; then
+		# Cache results
+		printf "%s %s %s %s %s %s %s\\n" \
+			"${celsius}" \
+			"${fahrenheit}" \
+			"${wind_speed_kmh}" \
+			"${wind_speed_mph}" \
+			"${icon_weather}" \
+			"${icon_wind_speed}" \
+			"${icon_wind_direction}" \
+			> "${file}"
+	else
+		if [ -f "${file}" ]; then
+			raw="$( cat "${file}" )"
+			celsius="$( echo "${raw}" | head -1 | awk '{print $1}' )"
+			fahrenheit="$( echo "${raw}" | head -1 | awk '{print $2}' )"
+			wind_speed_kmh="$( echo "${raw}" | head -1 | awk '{print $3}' )"
+			wind_speed_mph="$( echo "${raw}" | head -1 | awk '{print $4}' )"
+			icon_weather="$( echo "${raw}" | head -1 | awk '{print $5}' )"
+			icon_wind_speed="$( echo "${raw}" | head -1 | awk '{print $6}' )"
+			icon_wind_direction="$( echo "${raw}" | head -1 | awk '{print $7}' )"
+
+			format="[cache] ${format}"
+			force_warn=1
+		else
+			celsius="???"
+			fahrenheit="???"
+			wind_speed_kmh="???"
+			wind_speed_mph="???"
+			icon_weather="???"
+			icon_wind_speed="???"
+			icon_wind_direction="???"
+
+			force_crit=1
+		fi
+	fi
 }
 
 
@@ -416,7 +503,7 @@ get_status_color() {
 		if [ "${tg_sign[$i]}" = "=" ] || [ "${tg_sign[$i]}" = "!=" ]; then
 			pval="${!tg_placeholder[$i]}"
 		else
-			pval="$( echo "${!tg_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
+			pval="$( echo "${!tg_placeholder[$i]}" | grep -oE '\-?[0-9]*' | head -1 )"
 		fi
 
 		if [ "${tg_sign[$i]}" = "<" ]; then
@@ -443,7 +530,7 @@ get_status_color() {
 		if [ "${ti_sign[$i]}" = "=" ] || [ "${ti_sign[$i]}" = "!=" ]; then
 			pval="${!ti_placeholder[$i]}"
 		else
-			pval="$( echo "${!ti_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
+			pval="$( echo "${!ti_placeholder[$i]}" | grep -oE '\-?[0-9]*' | head -1 )"
 		fi
 
 		if [ "${ti_sign[$i]}" = "<" ]; then
@@ -470,7 +557,7 @@ get_status_color() {
 		if [ "${tw_sign[$i]}" = "=" ] || [ "${tw_sign[$i]}" = "!=" ]; then
 			pval="${!tw_placeholder[$i]}"
 		else
-			pval="$( echo "${!tw_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
+			pval="$( echo "${!tw_placeholder[$i]}" | grep -oE '\-?[0-9]*' | head -1 )"
 		fi
 
 		if [ "${tw_sign[$i]}" = "<" ]; then
@@ -499,7 +586,7 @@ get_status_color() {
 		if [ "${tc_sign[$i]}" = "=" ] || [ "${tc_sign[$i]}" = "!=" ]; then
 			pval="${!tc_placeholder[$i]}"
 		else
-			pval="$( echo "${!tc_placeholder[$i]}" | grep -oE '[0-9]*' | head -1 )"
+			pval="$( echo "${!tc_placeholder[$i]}" | grep -oE '\-?[0-9]*' | head -1 )"
 		fi
 
 		if [ "${tc_sign[$i]}" = "<" ]; then
@@ -563,7 +650,7 @@ replace_placeholders() {
 	done
 
 
-
+	#echo "${_format}"
 	# Replace placeholders in $format
 	for (( i=0; i < ${#format_nodes[@]}; i++ )); do
 		_search="${format_nodes[$i]}"
